chore: fix urls
edx/frontend-app-learner-dashboard pull request #29
Opened 2022-09-28 15:37 UTC by leangseu-edx

2022-09-29 15:29 UTC, nsprenkle commented on src/data/redux/app/selectors.js
> +    bannerImaSrc: baseAppUrl(course.bannerImgSrc),
Typo
```suggestion
    bannerImgSrc: baseAppUrl(course.bannerImgSrc),
```

2022-09-29 15:30 UTC, nsprenkle commented on .env.test
> +LEARNING_MICROFRONTEND_URL='http://localhost:2000'
Add missing newline
```suggestion
LEARNING_MICROFRONTEND_URL='http://localhost:2000'

```

2022-09-29 15:31 UTC, nsprenkle commented on .env.development
> +LEARNING_MICROFRONTEND_URL='http://localhost:2000'
Add missing newline
```suggestion
LEARNING_MICROFRONTEND_URL='http://localhost:2000'

```

2022-09-29 15:31 UTC, nsprenkle commented on .env.test
> +LEARNING_MICROFRONTEND_URL='http://localhost:2000'
See other 2 instances as well

2022-10-03 14:34 UTC, muselesscreator commented on src/containers/CourseCard/components/CourseCardActions/ViewCourseButton.jsx
> +      href={homeUrl}
This should stay as marketingUrl, I believe

2022-10-03 14:36 UTC, muselesscreator commented on src/data/redux/app/selectors.js
> +    marketingUrl: learningMfeUrl(courseRun.marketingUrl),
Not sure about the others, but this one is not in the learning MFE.

2022-10-03 14:36 UTC, muselesscreator commented on src/data/redux/app/selectors.js
> +    marketingUrl: learningMfeUrl(courseRun.marketingUrl),
(pretty sure...)

2022-10-03 14:37 UTC, muselesscreator requested changes
Couple of concerns around marketing URL, but beyond that looks good.

2022-10-03 14:38 UTC, muselesscreator commented
also looks like you are going to have some conflicts w/ my PR from end of week

2022-10-04 20:16 UTC, muselesscreator reviewed
LGTM as long as merges nicely :-p

2022-10-04 20:16 UTC, muselesscreator approved these changes
LGTM

2022-10-04 20:23 UTC, merged